title: "<%= siteName %>"
author:
  name: "<%= siteAuthor %>"
  email: '<%= siteEmail %>'
metadata:
  description: "<%= siteDescription %>"
  keywords: '<%= siteKeywords %>'
  copyright: '<%= siteClientName %>'
  author: '<%= siteClientName %>'
